package com.calculadora;

import javax.swing.JOptionPane;

public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }
    Calculadora cal = new Calculadora();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plCalculadora = new javax.swing.JPanel();
        lblCalculadora = new javax.swing.JLabel();
        lblCalculadoraIMG = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        lblValo2 = new javax.swing.JLabel();
        btnMultiplicacion = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        plConversor = new javax.swing.JPanel();
        lblConversor = new javax.swing.JLabel();
        lblConversorIMG = new javax.swing.JLabel();
        lblFah = new javax.swing.JLabel();
        txtFah = new javax.swing.JTextField();
        lblResC = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        btnLimpiarF = new javax.swing.JButton();
        btnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora y Conversor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plCalculadora.setBackground(new java.awt.Color(153, 153, 153));
        plCalculadora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCalculadora.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblCalculadora.setForeground(new java.awt.Color(102, 0, 0));
        lblCalculadora.setText("Calculadora Basica");
        plCalculadora.add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lblCalculadoraIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/calculadora/imagenes/calcular.png"))); // NOI18N
        plCalculadora.add(lblCalculadoraIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblValor1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(102, 0, 0));
        lblValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor1.setText("Valor1:");
        plCalculadora.add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        txtValor1.setBackground(new java.awt.Color(51, 51, 51));
        txtValor1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtValor1.setForeground(new java.awt.Color(255, 255, 255));
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plCalculadora.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 40));

        lblResultado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(102, 0, 0));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Resultado:");
        plCalculadora.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 40));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(51, 51, 51));
        txtResultado.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plCalculadora.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, 40));

        txtValor2.setBackground(new java.awt.Color(51, 51, 51));
        txtValor2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtValor2.setForeground(new java.awt.Color(255, 255, 255));
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plCalculadora.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, 40));

        lblValo2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblValo2.setForeground(new java.awt.Color(102, 0, 0));
        lblValo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValo2.setText("Valor2:");
        plCalculadora.add(lblValo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        btnMultiplicacion.setBackground(new java.awt.Color(51, 0, 0));
        btnMultiplicacion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiplicacion.setText("Multiplicar");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        plCalculadora.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 130, 50));

        btnSuma.setBackground(new java.awt.Color(51, 0, 0));
        btnSuma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("Sumar");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        plCalculadora.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, 50));

        btnLimpiar.setBackground(new java.awt.Color(51, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar datos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        plCalculadora.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 150, 50));

        btnResta.setBackground(new java.awt.Color(51, 0, 0));
        btnResta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 255, 255));
        btnResta.setText("Restar");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        plCalculadora.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 130, 50));

        btnDivision.setBackground(new java.awt.Color(51, 0, 0));
        btnDivision.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("Dividir");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        plCalculadora.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, 50));

        getContentPane().add(plCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 530));

        plConversor.setBackground(new java.awt.Color(102, 102, 102));
        plConversor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConversor.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblConversor.setForeground(new java.awt.Color(102, 0, 0));
        lblConversor.setText("Conversor °F");
        plConversor.add(lblConversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblConversorIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/calculadora/imagenes/baja-temperatura.png"))); // NOI18N
        plConversor.add(lblConversorIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblFah.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblFah.setForeground(new java.awt.Color(102, 0, 0));
        lblFah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFah.setText("Fahrenheit:");
        plConversor.add(lblFah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 40));

        txtFah.setBackground(new java.awt.Color(51, 51, 51));
        txtFah.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtFah.setForeground(new java.awt.Color(255, 255, 255));
        txtFah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plConversor.add(txtFah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, 40));

        lblResC.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblResC.setForeground(new java.awt.Color(102, 0, 0));
        lblResC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResC.setText("Resultado °C:");
        plConversor.add(lblResC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 40));

        txtCel.setEditable(false);
        txtCel.setBackground(new java.awt.Color(51, 51, 51));
        txtCel.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtCel.setForeground(new java.awt.Color(255, 255, 255));
        txtCel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plConversor.add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, 40));

        btnLimpiarF.setBackground(new java.awt.Color(51, 0, 0));
        btnLimpiarF.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpiarF.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarF.setText("Limpiar datos");
        btnLimpiarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFActionPerformed(evt);
            }
        });
        plConversor.add(btnLimpiarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 150, 50));

        btnConvertir.setBackground(new java.awt.Color(51, 0, 0));
        btnConvertir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        plConversor.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 50));

        getContentPane().add(plConversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 320, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char num = evt.getKeyChar();
        if((num < '0' || num > '9') && (num > ',' || num < '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char num = evt.getKeyChar();
        if((num < '0' || num > '9') && (num > ',' || num < '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtValor1.setText("");
        txtValor2.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        validarCampos();
        Double respuesta = cal.suma(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta+"");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        validarCampos();
        Double respuesta = cal.resta(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta+"");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        validarCampos();
        Double respuesta = cal.multiplicacion(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta+"");
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        validarCampos();
        Double respuesta = cal.division(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtResultado.setText(respuesta+"");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnLimpiarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFActionPerformed
        txtFah.setText("");
        txtCel.setText("");
    }//GEN-LAST:event_btnLimpiarFActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if(txtFah.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Error. El valor a convertir esta vacio.");
            txtFah.requestFocus();
            return;
        }
        Double fah = Double.parseDouble(txtFah.getText());
        txtCel.setText(String.format("%.4f", (fah - 32) * 5 / 9));
        
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void validarCampos() {
        if(txtValor1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Error. Valor 1 vacio.");
            txtValor1.requestFocus();
        }
        else if(txtValor2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Error. Valor 2 vacio.");
            txtValor2.requestFocus();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarF;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblCalculadoraIMG;
    private javax.swing.JLabel lblConversor;
    private javax.swing.JLabel lblConversorIMG;
    private javax.swing.JLabel lblFah;
    private javax.swing.JLabel lblResC;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblValo2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JPanel plCalculadora;
    private javax.swing.JPanel plConversor;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtFah;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
